### ISSUE TITLE
Running Blender GUI on other than main thread

### ISSUE THREAD

**Issue by darwin** [tristanstraub/blender-clj#2]
It sounds like linux is pretty flexible in this regard and allows running Blender GUI on a separate thread other than the main thread.

Unfortunately under macOS the situation seems to be much more strict. Some system libraries expect GUI to run on the main thread and throw/crash when it is not the case.

Here is an example of running the demo under macOS 10.15.5 as of debbf0e1936c7092dd3466d35050c97fa4f78c9d
https://gist.github.com/darwin/a6402b5e171982cc93f821e8b533397b

I don't know a good solution and haven't done any deeper research into this. I hope we can discuss this here and get better understanding of the issue. Ideas welcome. Thanks.

**Comment by darwin** [comment]
Just some quick thoughts. Let's assume Blender GUI must run on the main thread.

Then we have to somehow run the "ui_main" not via the future but directly on the java's main thread. But this will block REPL and other code running on the main thread. I'm not sure if this cause any major problems. But we can work around the blocked main thread. Before we call ui_main we can run nREPL server on a background thread (repl-thread) and drive our REPL session from a remote REPL client.

With the above solution we would have to make extra care to synchronize both threads. We cannot simply call Blender APIs from repl-thread. We have to do it from main thread and only if Blender is "ready for it". One trick is to work asynchronously, meaning to batch requests for api calls and register a timer with Blender. In the timer callback we are free to call batched Blender calls (we are on the main thread and Blender is ready for it).

If we were able to do the above. Another improvement would be to use stock Blender and start JVM inside (bootstrapping it with a python script) as [suggested here](https://www.reddit.com/r/Clojure/comments/gz947l/first_steps_scripting_blender_with_libpythonclj/ftgts0p/). In such case Blender has already running UI thread + Python interpretter and we additionally start JVM on a separate thread. The same synchronization requirements still apply.

With the improved situation the architecture would be quite similar to my [blender-clojure](https://github.com/darwin/blender-clojure). Where I don't inject JVM+libpython-clj but V8+naga and use it to drive cljs.

**Comment by tristanstraub** [comment]
Great work on getting it built!

The function blender-clj.core/with-context already does something similar to get code running through a timer. This made any calls to bpy.ops less likely to crash (while providing a context with "window" and "screen" entries as context overrides).

The future used for ui_main was pretty much written to avoid blocking the repl, so getting nrepl running first would work around this. At this point, we could simply patch blender to call "WM_main(C)" around the same place that "G.background = false" has been set.

https://github.com/tristanstraub/blender-clj/pull/3

**Comment by tristanstraub** [comment]
@darwin I've created a PR with nrepl in the background, and I believe with the ui in the foreground. Feel free to try it.
I've updated the README, and added ".dir-locals.el" for emacs/cider users, though I guess it might not be best practice, it is really convenient in my case.
You can run "clj -A:nREPL" and it starts blender and nrepl together, which you can then connect to remotely.
In the case of emacs, simply jacking in attaches the required cider middlewares, as per usual (possible because of .dir-locals.el changing the cider cli arguments).

**Comment by darwin** [comment]
@tristanstraub 

I just briefly tested it. And it is still crashing:
https://gist.github.com/darwin/f6db7436d1addf998902f36c19ca760b

To remove nREPL out of the picture I commented all references to it out. And in -main I simply run just `(ui-main)`. 

To confirm the fn is really called on the main thread I added:
```clj
(defn get-current-thread-info []
  (let [thread (Thread/currentThread)
        name (.getName thread)
        id (.getId thread)]
    (str name "[" id "]")))

(defn ui-main
  []
  (println (str "Running ui-main on thread:" (get-current-thread-info)))
...
```

You don't have to spend time on this. I will get back to it over the weekend and try to make it work somehow.

**Comment by darwin** [comment]
Maybe the Python interpreter does not run on the main thread. I guess libpython-clj might be running it on a separate thread...

**Comment by tristanstraub** [comment]
You could also try the project https://github.com/TylerGubala/blenderpy even though it isn't an officially supported project from blender, and it won't include the patch, though it may help diagnosing the problem. It could very well be that the patch change "G.background = false" is allowing something execute that shouldn't on MacOS.

I tried blenderpy, aswell as standard make, but get errors at runtime saying "You called InitGoogleLogging() twice!" and then crashes, but this might now be an incompatibility with an old xcode.

Same to you about working on it. No obligations. I find myself with a lot of free time at the moment, so haven't minded.

**Comment by tristanstraub** [comment]
So according to https://devtalk.blender.org/t/you-called-initgooglelogging-twice-error-on-embedded-blender-as-a-python-module/13372/2 I get the GoogleLogging error because it can't find the scripts, which is part of the error message I see. 
Surprisingly, the following worked, without giving me the error.

```sh
cd build_darwin
export BLENDER_SYSTEM_SCRIPTS=$(pwd)/2.90/scripts ;; don't forget BLENDEr-
python -c "import bpy"
```
[UPDATE: also needs BLENDER_SYSTEM_DATAFILES]

Unexpectedly, looks like I'm running 2.90 here. Guess that is a consequence of git cloning master.

**Comment by tristanstraub** [comment]
So, I've gotten it somewhat running on macos.

Running clj with "-J-XstartOnFirstThread" helped. The GUI now starts, but very slowly. The crash you are seeing is gone.

**Comment by tristanstraub** [comment]
So, if I wait long enough, it works correctly on macos, but I do need to maximize the blender window to get it to correctly recognizing the mouse events. I could run the examples from the repl. So, this proves to me that it will work under macos.
[UPDATE: I verified that a normal build of blender is also slow on my machine, but doesn't exhibit the same problems with recognizing mouse events.

**Comment by tristanstraub** [comment]
Well, I think my alternative project "clj-python-trampoline" is a better approach. It doesn't require patching blender, and blender can run as usual, on the main thread.

**Comment by pfeodrippe** [comment]
Not sure how this is going for stock blender now, but I have it working with jpype (I’m testing it on a Mac) https://github.com/pfeodrippe/vybe/blob/develop/basilisp/src/vybe/basilisp/jvm.lpy#L126. And, by combining it with jextract, it’s straightforward to read/write to blender memory.

**Comment by jobez** [comment]
> Not sure how this is going for stock blender now, but I have it working with jpype (I’m testing it on a Mac) https://github.com/pfeodrippe/vybe/blob/develop/basilisp/src/vybe/basilisp/jvm.lpy#L126. And, by combining it with jextract, it’s straightforward to read/write to blender memory.

hello! im revisiting the hankering many of us have for a more lispy-repl-y driven interaction with blender and found this project and this issue. is there somewhere where you walk through the necessary configuration of systems to get a clojure driven interaction going in blender?

**Comment by pfeodrippe** [comment]
> > Not sure how this is going for stock blender now, but I have it working with jpype (I’m testing it on a Mac) https://github.com/pfeodrippe/vybe/blob/develop/basilisp/src/vybe/basilisp/jvm.lpy#L126. And, by combining it with jextract, it’s straightforward to read/write to blender memory.
> 
> hello! im revisiting the hankering many of us have for a more lispy-repl-y driven interaction with blender and found this project and this issue. is there somewhere where you walk through the necessary configuration of systems to get a clojure driven interaction going in blender?

The main thing is to start the JVM from Blender using jpype setting the correct classpath, https://github.com/pfeodrippe/vybe/blob/develop/basilisp/src/vybe/basilisp/jvm.lpy#L173. I will try to make it more general, but you can try to do something using it and let me know about the result o/
